# Generated by Django 5.2.4 on 2025-07-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_price_per_ton_order_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cementtype',
            name='color',
            field=models.CharField(choices=[('🟦', "🟦 Ko'k"), ('🟩', '🟩 Yashil'), ('🟥', '🟥 Qizil'), ('🟨', '🟨 Sariq')], default='🟨', max_length=10),
            preserve_default=False,
        ),
    ]
