# Generated by Django 5.2.4 on 2025-08-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cementtype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_debt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cementtype',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Qizil'), ('#FFA500', "To'q sariq"), ('#FFFF00', 'Sariq'), ('#00B050', 'Yashil'), ('#0070C0', "To'q ko‘k"), ('#00B0F0', 'Moviy'), ('#002060', 'Ko‘k'), ('#7030A0', 'Binafsha'), ('#808080', 'Kulrang'), ('#000000', 'Qora')], max_length=10),
        ),
    ]
