# Generated by Django 5.2.4 on 2025-08-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_customer_default_debt_alter_cementtype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank', 'Perechesleniya'), ('cash', 'Naqd')], max_length=20, null=True),
        ),
    ]
